/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as PreOrderRouteImport } from './routes/pre-order'
import { Route as MasRouteImport } from './routes/mas'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductoProductIdRouteImport } from './routes/producto.$productId'

const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const PreOrderRoute = PreOrderRouteImport.update({
  id: '/pre-order',
  path: '/pre-order',
  getParentRoute: () => rootRouteImport,
} as any)
const MasRoute = MasRouteImport.update({
  id: '/mas',
  path: '/mas',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoProductIdRoute = ProductoProductIdRouteImport.update({
  id: '/producto/$productId',
  path: '/producto/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/mas': typeof MasRoute
  '/pre-order': typeof PreOrderRoute
  '/reservar': typeof ReservarRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/producto/$productId': typeof ProductoProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/mas': typeof MasRoute
  '/pre-order': typeof PreOrderRoute
  '/reservar': typeof ReservarRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/producto/$productId': typeof ProductoProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/mas': typeof MasRoute
  '/pre-order': typeof PreOrderRoute
  '/reservar': typeof ReservarRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/producto/$productId': typeof ProductoProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrito'
    | '/mas'
    | '/pre-order'
    | '/reservar'
    | '/sobre-nosotros'
    | '/producto/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrito'
    | '/mas'
    | '/pre-order'
    | '/reservar'
    | '/sobre-nosotros'
    | '/producto/$productId'
  id:
    | '__root__'
    | '/'
    | '/carrito'
    | '/mas'
    | '/pre-order'
    | '/reservar'
    | '/sobre-nosotros'
    | '/producto/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarritoRoute: typeof CarritoRoute
  MasRoute: typeof MasRoute
  PreOrderRoute: typeof PreOrderRoute
  ReservarRoute: typeof ReservarRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  ProductoProductIdRoute: typeof ProductoProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-order': {
      id: '/pre-order'
      path: '/pre-order'
      fullPath: '/pre-order'
      preLoaderRoute: typeof PreOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mas': {
      id: '/mas'
      path: '/mas'
      fullPath: '/mas'
      preLoaderRoute: typeof MasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$productId': {
      id: '/producto/$productId'
      path: '/producto/$productId'
      fullPath: '/producto/$productId'
      preLoaderRoute: typeof ProductoProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarritoRoute: CarritoRoute,
  MasRoute: MasRoute,
  PreOrderRoute: PreOrderRoute,
  ReservarRoute: ReservarRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  ProductoProductIdRoute: ProductoProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
